export const INIT_EXCEPTION_TABLE_ACTION = 'ExceptionTable/INIT_EXCEPTION_TABLE_ACTION';

export const INIT_EXCEPTION_DIMENTION_ACTION = 'ExceptionList/INIT_EXCEPTION_DIMENTION_ACTION';



export const HANDLE_TABLE_ACTION = 'ExceptionTable/HANDLE_TABLE_ACTION';
